### ISSUE TITLE
Bug in examples. Will not compile

### ISSUE THREAD

**Issue by johedlund** [davidepalladino/Button#1]
Tried some of the examples like longpresspullup 1.2.0
`void loop() {
    /* Checking the pressure and writing to Serial Monitor, if the press is short or long. */
    if (button1.checkPress() == 1) {
        Serial.println("SHORT PRESS!");
    } else if ((button1.checkPress() == -1) {
        Serial.println("LONG PRESS!");
    }
}` 

After _else if_ there is a parenthesis too much

Thanks for the library!

**Comment by davidepalladino** [comment]
Thank you for reporting. I will correct it for the new release.
I'm so happy for your utilization.

**Comment by davidepalladino** [comment]
Correct! See [version 1.2.1](https://github.com/davidepalladino/Button-Arduino/releases/tag/1.2.1).
