### ISSUE TITLE
PULLUP for ESP8266 nodemcu doesnt compile

### ISSUE THREAD

**Issue by getoledo** [davidepalladino/Button#2]
I tried pullup procedures example for nodemcu esp82666 and doesnt compile
Nice function,very useful. thanks

**Comment by davidepalladino** [comment]
Thanks for report and the use. The main problem concerns the symbolic constants `PULLUP` and `NO_PULLUP`. 
> For the boards of ESP family, the symbolic constant for PULLUP is INTERNAL_RESISTOR, and NO_PULLUP is EXTERNAL_RESISTOR

See this Wiki pages: [Constructors](https://github.com/davidepalladino/Button-Arduino/wiki/Constructors) / [Symbolic-constants](https://github.com/davidepalladino/Button-Arduino/wiki/Symbolic-constants)

Moreover, I'm preparing a version 2.x.x to unify the symbolic constants.

**Comment by getoledo** [comment]
thank you my friend

**Comment by davidepalladino** [comment]
Solved in new version 2.0.0!

**Comment by getoledo** [comment]
Awesome, thanks!
