### ISSUE TITLE
Long key press is not detected in version 2.0.0

### ISSUE THREAD

**Issue by RascalTheRaccoon** [davidepalladino/Button#4]
Hello,

I wrote a sketch for Arduino Nano using your Button-Arduino library version 1.2.1
It worked fine until I updated the version to 2.0.0 - after that the long-press could not be detected in the calibrate() routine inside "while (Kalibrierung == 4)". After I reversed back to 1.2.1 it works fine again.

`// Blinker Steuerung für Fahrzeug über Servo v1
// Nur für neue Platine Version 2
// Für Arduino UNO und NANO

// Letzte Änderung 20.11.2021

// Achtung, "Button-Arduino" Bibliothek Version 1.2.1 installieren, nicht auf Version 2.0.0 updaten!

#include <Button.h>                         // Bibliothek für Taster (mit Unterscheidung kurz/lang)
#include <Servo.h>                          // Bibliothek für Servo
#include <EEPROM.h>                         // Bibliothek für EEPROM

Button EingangTaster(12, PULLUP, 750);      // Eingang für Taster zum Aufruf der Kalibrierung
Button EingangBlinkerAus(A4);               // Eingang zum Setzen von Blinker Aus
Button EingangBlinkerLinks(A3, 750);        // Eingang zum Setzen von Blinker Links mit lang/kurz Unterscheidung
Button EingangBlinkerRechts(A5, 750);       // Eingang zum Setzen von Blinker Rechts mit lang/kurz Unterscheidung

Servo Servo1;

word Zeitinterval = 500;                    // Zeitinterval für LED Blinken in ms (0 bis 65535)
word Servo1ZeitBlinker;                     // Zeit für Blinker halten bei kurzer Betätigung in ms (0,5 bis 10 Sekunden)

word Servo1ZeitBlinkerAnalog = 512;         // Analoger Wert für Servo1 Zeit Blinker kurz (>= 0 und <= 1023)
word Servo1LinksAnalog = 512;               // Analoger Wert für Servo1 Drehung Links  (>= 0 und <= 1023)
word Servo1MitteAnalog = 512;               // Analoger Wert für Servo1 Mittelstellung (>= 0 und <= 1023)
word Servo1RechtsAnalog = 512;              // Analoger Wert für Servo1 Drehung Rechts (>= 0 und <= 1023)
word Servo1LinksPWM = 1500;                 // Impulslänge für Servo1 Drehung Links  (>= Servo1MinPWM und <= 1500)
word Servo1MittePWM = 1500;                 // Impulslänge für Servo1 Mittelstellung (>= Servo1MinPWM und <= Servo1MaxPWM)
word Servo1RechtsPWM = 1500;                // Impulslänge für Servo1 Drehung Rechts (>= 1500 und <= Servo1MaxPWM)

const int Servo1MinPWM = 1000;              // Minimum Impulslänge Servo1 bei Drehung Links (>= 544 und < 1500)
const int Servo1MaxPWM = 2000;              // Maximum Impulslänge Servo1 bei Drehung Rechts (> 1500 und <= 2400)
const int LED1 = LED_BUILTIN;               // Interne LED an Ausgang 13

byte Kalibrierung = 0;                      // Zähler für Kalibrierungs-Stufe
byte EEAdresse = 0;                         // Erste Speicher-Addresse für EEPROM
byte Zaehler = 0;                           // Zähler für LEDblink

const byte EingangPotiKalibrierung = A0;    // Analoger Eingang für Poti zur Einstellung der Servo Positionen

bool Servo1ResetAnforderung = false;        // Servo1 automatisch nach Zeit auf Mitte fahren (wahr/falsch)

unsigned long vorherigeZeitBlinken = 0;     // Vorherige Zeit für LEDblink()
unsigned long vorherigeZeitServo1 = 0;      // Vorherige Zeit für Servo1Reset()

void setup() {

  Serial.begin(115200);                     // Serielle Schnittstelle initializieren
  pinMode(LED1, OUTPUT);                    // Pin für LED1 als Ausgang definieren
  digitalWrite(LED1, LOW);                  // LED1 ausschalten

  // EEPROM Werte auslesen und an den Serial Monitor schicken:

  Servo1MittePWM = EEPROM.get(EEAdresse, Servo1MittePWM);
  EEAdresse += sizeof(word);
  Servo1LinksPWM = EEPROM.get(EEAdresse, Servo1LinksPWM);
  EEAdresse += sizeof(word);
  Servo1RechtsPWM = EEPROM.get(EEAdresse, Servo1RechtsPWM);
  EEAdresse += sizeof(word);
  Servo1ZeitBlinker = EEPROM.get(EEAdresse, Servo1ZeitBlinker);
  EEAdresse = 0;

  Serial.print("EEPROM Wert Servo1 Mitte: ");
  Serial.println(Servo1MittePWM, DEC);
  Serial.print("EEPROM Wert Servo1 Links: ");
  Serial.println(Servo1LinksPWM, DEC);
  Serial.print("EEPROM Wert Servo1 Rechts: ");
  Serial.println(Servo1RechtsPWM, DEC);
  Serial.print("EEPROM Wert Servo1 Zeit Blinker: ");
  Serial.println(Servo1ZeitBlinker, DEC);
  delay(500);

  Servo1.attach(3);                           // Servo1 an Pin X zuordnen (muß ein PWM Pin sein)
  Servo1.writeMicroseconds(Servo1MittePWM);   // Servo auf Mittelstellung fahren
  delay(250);
}

void loop() {

  if (EingangTaster.checkPress() == 1) {
    delay(500);
    Serial.println("Kalibrierung gestartet");
    calibrate();
  }

  if (EingangBlinkerAus.checkPress() == 1) {
//    Serial.print("Blinker Aus, Servo μs: ");
//    Serial.println(Servo1MittePWM);
    Servo1.writeMicroseconds(Servo1MittePWM);
    digitalWrite(LED1, LOW);

  } else if (EingangBlinkerLinks.checkPress() == 1) {
    digitalWrite(LED1, HIGH);
//    Serial.print("Blinker Links kurz, Servo μs: ");
//    Serial.println(Servo1LinksPWM);
    Servo1.writeMicroseconds(Servo1LinksPWM);
    vorherigeZeitServo1 = millis();
    Servo1ResetAnforderung = true;

  } else if (EingangBlinkerLinks.checkPress() == -1) {
    digitalWrite(LED1, HIGH);
//    Serial.print("Blinker Links lang, Servo μs: ");
//    Serial.println(Servo1LinksPWM);
    Servo1.writeMicroseconds(Servo1LinksPWM);

  } else if (EingangBlinkerRechts.checkPress() == 1) {
    digitalWrite(LED1, HIGH);
//    Serial.print("Blinker Rechts kurz, Servo μs: ");
//    Serial.println(Servo1RechtsPWM);
    Servo1.writeMicroseconds(Servo1RechtsPWM);
    vorherigeZeitServo1 = millis();
    Servo1ResetAnforderung = true;

  } else if (EingangBlinkerRechts.checkPress() == -1) {
    digitalWrite(LED1, HIGH);
//    Serial.print("Blinker Rechts lang, Servo μs: ");
//    Serial.println(Servo1RechtsPWM);
    Servo1.writeMicroseconds(Servo1RechtsPWM);
  }

  if (Servo1ResetAnforderung) {
    Servo1AutoReset();
  }
}

void calibrate() {

  Kalibrierung = 1;
  Serial.println("Kalibriere Servo1 Mitte");

  while (Kalibrierung == 1) {
    LEDblink();

    Servo1MitteAnalog = analogRead(EingangPotiKalibrierung);
    Serial.print("Poti Mitte analog: ");
    Serial.print(Servo1MitteAnalog);
    Servo1MittePWM = map(Servo1MitteAnalog, 0, 1023, Servo1MinPWM, Servo1MaxPWM);
    Serial.print("  Servo1 Mitte μs: ");
    Serial.println(Servo1MittePWM);
    Servo1.writeMicroseconds(Servo1MittePWM);

    if (EingangTaster.checkPress() == 1) {
      Serial.print("EEPROM Speicher Adresse: ");
      Serial.print(EEAdresse);
      Serial.print("  Wert Servo1 Mitte: ");
      Serial.println(Servo1MittePWM);
      EEPROM.put(EEAdresse, Servo1MittePWM);
      delay(100);
      EEAdresse += sizeof(word);
      Kalibrierung = 2;
      Serial.println("Kalibriere Servo1 Links");
    }

    while (Kalibrierung == 2) {
      LEDblink();

      Servo1LinksAnalog = analogRead(EingangPotiKalibrierung);
      Serial.print("Poti Links analog: ");
      Serial.print(Servo1LinksAnalog);
      Servo1LinksPWM = map(Servo1LinksAnalog, 0, 1023, Servo1MinPWM, Servo1MaxPWM);
      Serial.print("  Servo1 Links μs: ");
      Serial.println(Servo1LinksPWM);
      Servo1.writeMicroseconds(Servo1LinksPWM);

      if (EingangTaster.checkPress() == 1) {
        Serial.print("EEPROM Speicher Adresse: ");
        Serial.print(EEAdresse);
        Serial.print("  Wert Servo 1 Links: ");
        Serial.println(Servo1LinksPWM);
        EEPROM.put(EEAdresse, Servo1LinksPWM);
        delay(100);
        EEAdresse += sizeof(word);
        Kalibrierung = 3;
        Serial.println("Kalibriere Servo1 Rechts");
      }

      while (Kalibrierung == 3) {
        LEDblink();

        Servo1RechtsAnalog = analogRead(EingangPotiKalibrierung);
        Serial.print("Poti Rechts analog: ");
        Serial.print(Servo1RechtsAnalog);
        Servo1RechtsPWM = map(Servo1RechtsAnalog, 0, 1023, Servo1MinPWM, Servo1MaxPWM);
        Serial.print("  Servo1 Rechts μs: ");
        Serial.println(Servo1RechtsPWM);
        Servo1.writeMicroseconds(Servo1RechtsPWM);

        if (EingangTaster.checkPress() == 1) {
          Serial.print("EEPROM Speicher Adresse: ");
          Serial.print(EEAdresse);
          Serial.print("  Wert Servo1 Rechts: ");
          Serial.println(Servo1RechtsPWM);
          EEPROM.put(EEAdresse, Servo1RechtsPWM);
          delay(100);
          EEAdresse += sizeof(word);
          Kalibrierung = 4;
          Servo1.writeMicroseconds(Servo1MittePWM);
          Serial.println("Kalibriere Zeit für Blinker kurz ... ");
        }

        while (Kalibrierung == 4) {
          LEDblink();

          Servo1ZeitBlinkerAnalog = analogRead(EingangPotiKalibrierung);
          Serial.print("Poti Zeit analog: ");
          Serial.print(Servo1ZeitBlinkerAnalog);
          Servo1ZeitBlinker = map(Servo1ZeitBlinkerAnalog, 1, 1023, 10000, 500);
          Serial.print("  Servo1 Zeit Blinker ms: ");
          Serial.println(Servo1ZeitBlinker);

          if (EingangTaster.checkPress() == 1) {
            Servo1.writeMicroseconds(Servo1LinksPWM);
            delay(Servo1ZeitBlinker);
            Serial.print("Blinker Aus, Servo μs: ");
            Serial.println(Servo1MittePWM);
            Servo1.writeMicroseconds(Servo1MittePWM);
          }

          if (EingangTaster.checkPress() == -1) {
            Serial.print("EEPROM Speicher Adresse: ");
            Serial.print(EEAdresse);
            Serial.print("  Wert Servo1 Zeit Blinker: ");
            Serial.println(Servo1ZeitBlinker);
            EEPROM.put(EEAdresse, Servo1ZeitBlinker);
            delay(100);
            EEAdresse = 0;
            Kalibrierung = 0;
            Serial.println("Kalibrierung beendet ... ");
            digitalWrite(LED1, HIGH);
            delay(2000);
            digitalWrite(LED1, LOW);
            Servo1.writeMicroseconds(Servo1MittePWM);
            Serial.println("Starte Programm ...");
            return;
          }
        }
      }
    }
  }
}

void Servo1AutoReset() {

  unsigned long aktuelleZeit = millis();

  if (aktuelleZeit - vorherigeZeitServo1 >= Servo1ZeitBlinker) {

//    Serial.print("Blinker Aus, Servo μs: ");
//    Serial.println(Servo1MittePWM);
    Servo1.writeMicroseconds(Servo1MittePWM);
    digitalWrite(LED1, LOW);
    Servo1ResetAnforderung = false;

  } else {
    return;
  }
}

void LEDblink() {

  unsigned long aktuelleZeit = millis();

  if (aktuelleZeit - vorherigeZeitBlinken >= Zeitinterval) {
    digitalWrite(LED1, HIGH);

    if (Zaehler < Kalibrierung) {
      vorherigeZeitBlinken = aktuelleZeit;
      Zeitinterval = 500;
      Zaehler++;

    } else {
      Zaehler = 1;
      vorherigeZeitBlinken = aktuelleZeit;

      if (Kalibrierung == 1) {
        return;
      }

      Zeitinterval = Zeitinterval + 500;
    }
  } else {
    digitalWrite(LED1, LOW);
  }
  return;
}`

**Comment by davidepalladino** [comment]
Hi,
thank you for the feedback. From version 1.1.2 to version 2.0.0 there are several improvements. Firstly, you cannot use the symbolic constant `PULLUP`, but `B_PULLUP`. I don't know if the utilization is related to use the version 1.1.2.
Anyway, in this new major version has been changed the behavior of `checkPress()`, method, in accord to issue #3; in particular _"method doesn't return the same result if the button is still pressed, both for short and long"_, like wrote in changelog.
The main purpose of this class is to return a single value, even if the button is still pressed; else, the behavior of long press it would have been like the `digitalRead()` function of Arduino core. 

Now, this is not the only relevant feature of this last version: has been removed the privates methods to improve the performance.

By virtue of this, you have two roads to choice:
1. continue to use the 1.1.2 version;
2. to use the new version re-evaluating your code, maybe considering to use the `digitalRead()` function if the button of your project is an end stop or similar, where the value will be still similar during the long press of button.

I hope I have been clear in this response, and to help you to a solution.
